gemini_api_key = "AQ.Ab8RN6LLonvThiCOJvfzhmBV_ujlhDEzcAI367LFS_OFg87T5A"
groq_api_key = "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"
openai_api_key = "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"
deepseek_api_key = "sk-63cb83fbbc30499abd2241b362edebcd"